### ISSUE TITLE
The time blocking app overview

### ISSUE THREAD

**Issue by laila-nabil** [laila-nabil/thetimeblockingapp#29]
### 0.Setup
   - [x]  laila-nabil/thetimeblockingapp#30  [Design Task] App wireframe ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#34 [Task] Setup code project ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#32 [Task] AppBar widget ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#33 [Task] Drawer widget ✅ Iteration 1: MVP Milestone
 
---
### 1. laila-nabil/thetimeblockingapp#11  User Authentication Feature

   - [x] laila-nabil/thetimeblockingapp#5 [User story] As a user, I would like to add my registration details so that I can create an account.✅ Iteration 1: MVP Milestone   
   - [x] laila-nabil/thetimeblockingapp#10  [User story] As a user, I would like to login so that I can access my account. ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#68 Onboarding before Authentication explaining why authenticating with Clickup 🔥 Iteration 2: MVP as design Milestone

---
### 2. laila-nabil/thetimeblockingapp#26  Task management Feature

   - [x] laila-nabil/thetimeblockingapp#25 [Sub-Feature] Schedule page ✅ Iteration 1: MVP Milestone
     - [x]  laila-nabil/thetimeblockingapp#31  [Task] Calendar Widget as UI✅ Iteration 1: MVP Milestone
     - [x] laila-nabil/thetimeblockingapp#37  [Task] Add/Edit task pop up Widget as UI ✅ Iteration 1: MVP Milestone
     - [x] laila-nabil/thetimeblockingapp#39 [User Story] Edit an existing task ✅ Iteration 1: MVP Milestone
     - [x] laila-nabil/thetimeblockingapp#41 Calendar in Schedule page ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#13 [Sub-Feature] Add Task ✅ Iteration 1: MVP Milestone
     - laila-nabil/thetimeblockingapp#37  [Task] Add/Edit task pop up Widget as UI ✅ Iteration 1: MVP Milestone
     - [x] laila-nabil/thetimeblockingapp#38 [User Story] Create a Task in Schedule App via Time Slot, + Button, Tag Page, or List Page ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#14 [Sub-Feature]  Task actions ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#18 [Sub-Feature] Tags page✅ Iteration 1: MVP Milestone
     -  laila-nabil/thetimeblockingapp#38 [User Story] Create a Task in Schedule App via Time Slot, + Button, Tag Page, or List Page ✅ Iteration 1: MVP Milestone
     - laila-nabil/thetimeblockingapp#39 [User Story] Edit an existing task ✅ Iteration 1: MVP Milestone
   - [x] laila-nabil/thetimeblockingapp#19 [Sub-Feature]  Lists page ✅ Iteration 1: MVP Milestone
     - laila-nabil/thetimeblockingapp#38 [User Story] Create a Task in Schedule App via Time Slot, + Button, Tag Page, or List Page ✅ Iteration 1: MVP Milestone
     - laila-nabil/thetimeblockingapp#39 [User Story] Edit an existing task ✅ Iteration 1: MVP Milestone

---
### 3.Setup with actual UIUX design
   - [x] laila-nabil/thetimeblockingapp#35  Design Task] App UI/UX design 🔥 Iteration 2: MVP as design Milestone
   - [x] laila-nabil/thetimeblockingapp#60  Main components 🔥 Iteration 2: MVP as design Milestone
---
### 4. laila-nabil/thetimeblockingapp#63   Task management Feature

   - [ ] laila-nabil/thetimeblockingapp#50 [Sub-Feature] Schedule page as design 🔥 Iteration 2: MVP as design Milestone
     - [ ] laila-nabil/thetimeblockingapp#61  [Task] Calendar Widget as UI as design 🔥 Iteration 2: MVP as design Milestone
     - [ ] laila-nabil/thetimeblockingapp#59  [Task] Add/Edit task  UI as design 🔥 Iteration 2: MVP as design Milestone
     - [ ] laila-nabil/thetimeblockingapp#56  Calendar in Schedule page as design 🔥 Iteration 2: MVP as design Milestone
   - [ ] laila-nabil/thetimeblockingapp#55 [Sub-Feature] Add/Edit Task as design 🔥 Iteration 2: MVP as design Milestone
     - laila-nabil/thetimeblockingapp#59  [Task] Add/Edit task UI as design 🔥 Iteration 2: MVP as design Milestone
     - [ ] laila-nabil/thetimeblockingapp#58  [User Story] Create/Edit a Task in Schedule App via Time Slot, + Button, Tag Page, or List Page as design 🔥 Iteration 2: MVP as design Milestone
   - [x] laila-nabil/thetimeblockingapp#51  Tags/Lists page as design 🔥 Iteration 2: MVP as design Milestone
     -  laila-nabil/thetimeblockingapp#58  [User Story] Create/Edit a Task in Schedule App via Time Slot, + Button, Tag Page, or List Page as design 🔥 Iteration 2: MVP as design Milestone
   - [ ] laila-nabil/thetimeblockingapp#15  [Sub-Feature] Search functionality
   - [ ] laila-nabil/thetimeblockingapp#24 [Sub-Feature] Maps and locations for tasks
   - [ ] laila-nabil/thetimeblockingapp#20  [Sub-Feature]  Auto Schedule tasks

---
### 6. laila-nabil/thetimeblockingapp#16  Settings Feature

---
### 7. laila-nabil/thetimeblockingapp#7 [Design Task] Authentication flow UI design

---
### 8.  laila-nabil/thetimeblockingapp#17  Feedback Feature

---
### 9. laila-nabil/thetimeblockingapp#12 Onboarding Feature
   - [ ]  laila-nabil/thetimeblockingapp#27  [User Story] As a new user exploring the app's demo/tutorial during onboarding, I want to add a task to the calendar without having to log in or sign up, So that I can get a glimpse of the app's functionality and experience its features. 
     - [ ]  laila-nabil/thetimeblockingapp#28  [Task] Demo at startup of how to use the app to add a task to the calendar

---
### 10. laila-nabil/thetimeblockingapp#21 Keyboard shortcuts
